apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvizion-mysql
  namespace: myvizion-web-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myvizion-mysql
  template:
    metadata:
      labels:
        app: myvizion-mysql
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: myvizion-mysql-storage
          persistentVolumeClaim:
            claimName: myvizion-mysql-pvc
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: myvizion-mysql-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: MYSQL_USERNAME
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: mysql-database
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
