apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myvizion-webcert
  namespace: default
spec:
  dnsNames:
    - myvizion.net
  secretName: myvizion-webtls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer