apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvizion-webimage
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php 
      template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: myvizion-webimage
        image: myvizion/website
        ports:
        - containerPort: 80