apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvizion-webimage
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: myvizion-webimage
        image: myvizion/website
        ports:
        - containerPort: 80