apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myvizion-webingress
spec:
  tls:
  - hosts:
    - myvizion.net
    secretName: myvizion-webtls
  rules:
  - host: myvizion.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myvizion-webservice
            port:
              number: 80
