apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myvizion-web-cert
  namespace: myvizion-web-ns
spec:
  dnsNames:
    - myvizion.net
  secretName: myvizion-web-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer