apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvizion-web
  namespace: myvizion-web-ns
  labels:
    app: myvizion-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myvizion-web
  template:
    metadata:
      labels:
        app: myvizion-web
    spec:
      containers:
      - name: myvizion-web
        image: myvizion/website
        imagePullPolicy: Always
        ports:
        - containerPort: 80