apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvizion-web
  namespace: myvizion-web-ns
  labels:
    app: myvizion-web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: myvizion-web
  template:
    metadata:
      labels:
        app: myvizion-web
    spec:
      containers:
      - name: myvizion-web
        image: myvizion/website
        imagePullPolicy: Always
        resources:
          limits:
            memory: 350Mi
            cpu: "0.5"
          requests:
            memory: 300Mi
            cpu: "0.25"
        ports:
        - containerPort: 80